// <auto-generated />
using System;
using CTN4_Data.DB_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CTN4_Data.Migrations
{
    [DbContext(typeof(DB_CTN4_ok))]
    [Migration("20231019024233_ssf")]
    partial class ssf
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Anh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("TenAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("Anhs");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChatLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenChatLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ChatLieus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cd64173b-b470-45a9-9cda-0d90d70096f3"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Da PU cao cấp",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("248c839c-b536-4b99-8ba7-052d23bc55e0"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Da PU mềm mịn, cao cấp",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("04d787eb-4ed2-434f-8bb6-c537c350349c"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Vai Canvat",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("58cd19a9-39b5-4432-bca3-d0c0069bb56c"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Da tổng hợp",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChiTietSanPhamYeuThich", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamYeuThich")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.HasIndex("IdSanPhamYeuThich");

                    b.ToTable("ChiTietSanPhamYeu");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChucVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ChucVus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d16ac357-3ced-4c2c-bcdc-d38971214414"),
                            TenChucVu = "Quản lý",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("56dd3ee2-c4df-4376-b982-e2c0f70877e9"),
                            TenChucVu = "Nhân viên",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DanhMuc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DanhMucs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c9cbe9c-2259-405a-9e17-68b7b51580cd"),
                            Is_detele = true,
                            TenDanhMuc = "Túi đeo chéo Nữ – Cross body"
                        },
                        new
                        {
                            Id = new Guid("e5fbdffc-d9f2-4ae6-a80f-cc55de606827"),
                            Is_detele = true,
                            TenDanhMuc = "Túi đeo vai – Shoulder bag"
                        },
                        new
                        {
                            Id = new Guid("5519de51-5e1c-4e1c-92de-efb573b00a68"),
                            Is_detele = true,
                            TenDanhMuc = "Túi tote"
                        },
                        new
                        {
                            Id = new Guid("3a566c9c-9431-4c76-beab-1c39e0a92a48"),
                            Is_detele = true,
                            TenDanhMuc = "Túi satchel"
                        },
                        new
                        {
                            Id = new Guid("1da7b42f-f68f-4431-b6fc-f80ecb6aee92"),
                            Is_detele = true,
                            TenDanhMuc = "Túi baguette"
                        },
                        new
                        {
                            Id = new Guid("b311ece3-2e00-4e18-a52a-dece8a2c9d1a"),
                            Is_detele = true,
                            TenDanhMuc = "Túi bao tử – Túi bumbag"
                        },
                        new
                        {
                            Id = new Guid("5f3b0a78-e527-4d26-9323-c33d2a1c49f8"),
                            Is_detele = true,
                            TenDanhMuc = "Túi cầm tay – Clutch"
                        },
                        new
                        {
                            Id = new Guid("28099712-aea9-4cfa-b442-57ec402a1ac3"),
                            Is_detele = true,
                            TenDanhMuc = "Túi Hobo"
                        },
                        new
                        {
                            Id = new Guid("d1f2df4d-b005-4727-9e90-dc2e7f4eacc5"),
                            Is_detele = true,
                            TenDanhMuc = "Túi dây rút – Pouch"
                        },
                        new
                        {
                            Id = new Guid("75c22eba-b63b-464b-835d-b9dbe4d3e056"),
                            Is_detele = true,
                            TenDanhMuc = "Túi Bucket"
                        },
                        new
                        {
                            Id = new Guid("05559b27-5d67-41a8-a203-e05b56e535b4"),
                            Is_detele = true,
                            TenDanhMuc = "Túi Bowling"
                        },
                        new
                        {
                            Id = new Guid("14c2ea6d-4881-4b2d-80b5-7caf57d7d399"),
                            Is_detele = true,
                            TenDanhMuc = "Túi Ring Bag"
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DanhMucChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDanhMuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdDanhMuc");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("DanhMucChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DiaChiNhanHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenDiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("DaiChiNhanHangs");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GiamGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("DieuKienGiam")
                        .HasColumnType("real");

                    b.Property<string>("MaGiam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<float>("SoTienGiam")
                        .HasColumnType("real");

                    b.Property<float>("SoTienGiamToiDa")
                        .HasColumnType("real");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GiamGias");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GiamGiaChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdGiamGia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdGiamGia");

                    b.HasIndex("IdHoaDon");

                    b.ToTable("GiamGiaChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GioHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdGioHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdGioHang");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("GioHangChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdDiaChiNhanHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPhuongThuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGiao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTaoHoaDon")
                        .HasColumnType("datetime2");

                    b.Property<float>("TongTien")
                        .HasColumnType("real");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDiaChiNhanHang");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdPhuongThuc");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("GiaTien")
                        .HasColumnType("real");

                    b.Property<Guid?>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("HoaDonChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhachHangs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d16ac357-3ced-4c2c-bcdc-d38971214499"),
                            AnhDaiDien = "",
                            DiaChi = "Hà Nội",
                            Email = "thieubvph20221@gmail.com",
                            GioiTinh = "Nam",
                            Ho = "Bùi Văm",
                            Is_detele = true,
                            MatKhau = "thieuxk",
                            SDT = "0912384746",
                            Ten = "Thiều",
                            TenDangNhap = "thieuxk",
                            Trangthai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_Detele")
                        .HasColumnType("bit");

                    b.Property<string>("MaKhuyenMai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanTramGiamGia")
                        .HasColumnType("int");

                    b.Property<float>("SoTienGiam")
                        .HasColumnType("real");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMaiPhanLoai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPhanLoai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("idKhuyenMai")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdPhanLoai");

                    b.HasIndex("idKhuyenMai");

                    b.ToTable("KhuyenMaiPhanLoais");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMaiSanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdkhuyenMai")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.HasIndex("IdkhuyenMai");

                    b.ToTable("KhuyenMaiSanPhams");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Mau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenMau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Maus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6843ac11-2306-4fd0-aa33-6e0587f2365e"),
                            Is_detele = true,
                            TenMau = "đen",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("b4236ea5-139c-4e2b-89f7-4b5dba1377aa"),
                            Is_detele = true,
                            TenMau = "trắng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("897278c8-c656-47d9-a5a3-fcd87a334586"),
                            Is_detele = true,
                            TenMau = "nâu",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("ff0357f9-bad0-4461-b660-a13d915d7815"),
                            Is_detele = true,
                            TenMau = "xám",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("fa174365-c5ed-4884-a396-f326d4aa5d65"),
                            Is_detele = true,
                            TenMau = "vàng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("493946ec-5bac-4e27-8bb6-7584b397fc1d"),
                            Is_detele = true,
                            TenMau = "ghi",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("c96a331b-e520-41d7-b30d-bd366d054140"),
                            Is_detele = true,
                            TenMau = "cam",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("b6087fff-77ad-438c-a60f-4b2f22ddc33f"),
                            Is_detele = true,
                            TenMau = "xanh dương đậm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("98291742-1a81-4234-841d-addb1c50dc65"),
                            Is_detele = true,
                            TenMau = "xanh lục",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("960e0bc3-9033-448e-9683-321e36d6e4d5"),
                            Is_detele = true,
                            TenMau = "xanh dương",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("ecc1be51-bf6c-424d-9419-7c2ca72b9ba1"),
                            Is_detele = true,
                            TenMau = "xanh lá",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("5ed43e92-bf74-4631-b58c-e0e8fe2fe01a"),
                            Is_detele = true,
                            TenMau = "xanh nhạt",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("ccb33494-ad8c-411f-91d5-15d327ff7abe"),
                            Is_detele = true,
                            TenMau = "tràm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("b1f4f5d6-49bd-4b82-80c1-e344d5ac7839"),
                            Is_detele = true,
                            TenMau = "tím",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("ab877769-afe3-48f3-9faf-580bbce09cdd"),
                            Is_detele = true,
                            TenMau = "xanh lá đậm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("9bc658e1-04e0-4496-84fd-b5be0e0ac144"),
                            Is_detele = true,
                            TenMau = "xanh tím",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("a714dbe5-40c9-4034-80e1-f23c9f3201f6"),
                            Is_detele = true,
                            TenMau = "hồng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("28bb2b32-77ca-41cc-b14a-ac2f60cea81d"),
                            Is_detele = true,
                            TenMau = "kem",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("f613a489-3477-4832-acb1-8bb5ecef963f"),
                            Is_detele = true,
                            TenMau = "kem Đậm",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdChucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdChucVu");

                    b.ToTable("NhanViens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d783d65-0ebd-4a6e-85bf-d91ee63a28b1"),
                            AnhDaiDien = "",
                            DiaChi = "Hà Nội",
                            Email = "nothing@gmail.com",
                            GioiTinh = "Nữ",
                            Ho = "Nguyễn",
                            IdChucVu = new Guid("d16ac357-3ced-4c2c-bcdc-d38971214414"),
                            MatKhau = "12345678",
                            SDT = "0912384746",
                            Ten = "Trang",
                            TenDangNhap = "trangnt34",
                            Trangthai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.NSX", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenNSX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("NSXs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c42df94e-b4ec-4961-94c2-9155fb9e7b7d"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Juno",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("e5e4601b-05bd-40c4-b862-2d68dfaabc64"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Prada",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("c5e974ba-8bad-4a92-b77a-7ff32360a146"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Gucci",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("9065c787-92ce-4aff-a7f1-5393f41d0dd6"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Chanel",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("a76fb944-e667-44a5-8c60-149019d3002e"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Coach",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("775760de-eee2-4914-8fbd-9b8e5f3b18cf"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "MLB Korea",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("fca257fe-133c-488b-b1b1-2781414a3bd3"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Michael Kors",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("9f6a1660-d843-4797-b35d-b29354e8cf51"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "JW Anderson",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("fdf0b4a2-4e1f-4e5a-9736-99c8faedf63a"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Christian Dior",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("c96c9f7d-f403-4a2d-894b-d7ec4070562d"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Louis Vuitton",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhanLoai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Delete")
                        .HasColumnType("bit");

                    b.Property<string>("TenPhanLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrạngThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PhanLoais");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhanLoaiChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPhanLoai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdPhanLoai");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("PhanLoaiChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhuongThucThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenPhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PhuongThucThanhToans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d16ac357-3ced-4c2c-bcdc-d38971211111"),
                            Is_detele = true,
                            TenPhuongThuc = "Thanh toán khi nhận hàng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("d16ac357-3ced-4c2c-bcdc-d38971211112"),
                            Is_detele = true,
                            TenPhuongThuc = "Thanh toán tại cửa hàng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("d16ac357-3ced-4c2c-bcdc-d38971211113"),
                            Is_detele = true,
                            TenPhuongThuc = "Thanh toán qua ngân hàng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("d16ac357-3ced-4c2c-bcdc-d38971211114"),
                            Is_detele = true,
                            TenPhuongThuc = "Thanh toán qua VNpay",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fae46c93-fa1a-49cc-82ef-a88e8059b4bf"),
                            AnhDaiDien = "TXT Da Rắn Khóa Bạc _QuanChau_Trang_Da PU cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TXT Da Rắn Khóa Bạc _QuanChau_Trang_Da PU cao cấp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("73917342-6e38-4697-9f26-a61b66d14734"),
                            AnhDaiDien = "TXT Phủ Màu Tag Vuông_QuanChau_XanhLuc_Da PU mềm mịn, cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TXT Phủ Màu Tag Vuông_QuanChau_XanhLuc_Da PU mềm mịn, cao cấp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("759339e8-205f-4ae3-9240-d03afc11a218"),
                            AnhDaiDien = "TDV Hobo Đáy Tròn_QuanChau_Trang_Da lộn, da PU cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TDV Hobo Đáy Tròn_QuanChau_Trang_Da lộn, da PU cao cấp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("0121e5d0-767b-4174-a907-766f1369a8d1"),
                            AnhDaiDien = "Túi Xách Nhỏ Curve 1_Trung Quốc_Xanhduong_Da tổng hợp(1).webp",
                            Is_detele = true,
                            TenSanPham = "Túi Xách Nhỏ Curve 1_Trung Quốc_Xanhduong_Da tổng hợp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("46037f33-91ce-4df7-a29d-c55540f1f460"),
                            AnhDaiDien = "TDV Hobo Đáy Tròn_QuanChau_Xanh-Duong_Da lộn, da PU cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TDV Hobo Đáy Tròn_QuanChau_Xanh-Duong_Da lộn, da PU cao cấp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("01c37cb0-826a-4521-91f1-ceff3f753ec5"),
                            AnhDaiDien = "TOT Classic Phối Màu _QuanChau_Ghi_Da PU mềm mịn, cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TOT Classic Phối Màu _QuanChau_Ghi_Da PU mềm mịn, cao cấp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("450af072-be9c-4283-a2ca-7e33f2bb1417"),
                            AnhDaiDien = "TOT Classic Phối Màu _QuanChau_Nau_Da PU mềm mịn, cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TOT Classic Phối Màu _QuanChau_Nau_Da PU mềm mịn, cao cấp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("358780e8-3d55-4990-bd6e-cadd801431c2"),
                            AnhDaiDien = "Túi Xách Nhỏ Curve 1_Trung Quốc_XanhLa_Da tổng hợp(1).webp",
                            Is_detele = true,
                            TenSanPham = "Túi Xách Nhỏ Curve 1_Trung Quốc_XanhLa_Da tổng hợp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("9de10027-e4d3-469a-9e0c-b42b13a10371"),
                            AnhDaiDien = "Túi Xách Nhỏ Đeo Vai - Cycling_Trung Quốc_XanhNhat_Da tổng hợp(1).webp",
                            Is_detele = true,
                            TenSanPham = "Túi Xách Nhỏ Đeo Vai - Cycling_Trung Quốc_XanhNhat_Da tổng hợp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("dfd8ae8a-05ec-41bf-b863-6d842b821c7b"),
                            AnhDaiDien = "TDV Hobo Quai Ngắn_QuanChau_Trang_Da PU mềm mịn, cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TDV Hobo Quai Ngắn_QuanChau_Trang_Da PU mềm mịn, cao cấp(1)",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GiaBan")
                        .HasColumnType("real");

                    b.Property<float>("GiaNhap")
                        .HasColumnType("real");

                    b.Property<float>("GiaNiemYet")
                        .HasColumnType("real");

                    b.Property<Guid?>("IdChatLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMau")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNSX")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSize")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("MaSp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdChatLieu");

                    b.HasIndex("IdMau");

                    b.HasIndex("IdNSX");

                    b.HasIndex("IdSize");

                    b.HasIndex("IdSp");

                    b.ToTable("SanPhamChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamYeuThich", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("SanPhamYeuThichs");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb6d6926-2670-4c68-8f0f-157acffe84ad"),
                            Is_detele = true,
                            TenSize = "30cm x 20cm x 10cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("9d6de375-ed2a-48a6-ae7a-eb060431cc37"),
                            Is_detele = true,
                            TenSize = "28cm x 22cm x 10cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("f9e835a4-d24e-458c-b050-6edf0f35fc7f"),
                            Is_detele = true,
                            TenSize = "27cm x 12cm x 8cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("75d1f85c-b525-425e-8985-a8483df85cb2"),
                            Is_detele = true,
                            TenSize = "23cm x 13cm x 6cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("427d3f75-77c8-4618-ade0-4642a2c85b53"),
                            Is_detele = true,
                            TenSize = "23cm x 15cm x 5cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("7dc14f60-2605-464a-af20-8ceddde479ff"),
                            Is_detele = true,
                            TenSize = "22cm x 18cm x 8cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("4669ec8e-707b-4c53-a6e0-a8534d201346"),
                            Is_detele = true,
                            TenSize = "20cm x 12cm x 7cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("88f407e1-bc6e-4ea0-b3e2-1285325c39c6"),
                            Is_detele = true,
                            TenSize = "22cm x 15cm x 6cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("d9f1ff82-fd0a-4fda-9360-fbb04a70d87b"),
                            Is_detele = true,
                            TenSize = "17cm x 16cm x 7cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("13eed462-ad61-4469-ad71-a6856465b544"),
                            Is_detele = true,
                            TenSize = "22cm x 12cm x 6cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("e28ad8ef-9bb3-4d4b-819f-f25c598192b4"),
                            Is_detele = true,
                            TenSize = "21cm x 8cm x 13cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("22956819-7801-4422-aabd-2813957141ac"),
                            Is_detele = true,
                            TenSize = "27cm x 6cm x 19cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("301b19df-4a36-4f7f-8096-9f0c60c33706"),
                            Is_detele = true,
                            TenSize = "20cm x 6cm x 13cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("4c415138-725c-48a4-9943-1288ee207617"),
                            Is_detele = true,
                            TenSize = "37cm x 13cm x 28cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("4651ec3c-b70a-4537-bcb6-eb395019675d"),
                            Is_detele = true,
                            TenSize = "20cm x 13.5cm x 7.5cm ",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("5ee1511c-27c1-4f5f-a23d-da33c385f60d"),
                            Is_detele = true,
                            TenSize = "19cm x 13cm x 7cm",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Anh", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("Anhs")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChiTietSanPhamYeuThich", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("CTietSanPhamYeuThiches")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamYeuThich", "SanPhamYeuThich")
                        .WithMany("CTietSanPhamYeuThiches")
                        .HasForeignKey("IdSanPhamYeuThich");

                    b.Navigation("SanPhamChiTiet");

                    b.Navigation("SanPhamYeuThich");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DanhMucChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.DanhMuc", "DanhMuc")
                        .WithMany("DanhMucChiTiets")
                        .HasForeignKey("IdDanhMuc");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("DanhMucChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.Navigation("DanhMuc");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DiaChiNhanHang", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhachHang", "KhachHang")
                        .WithMany("DiaChiNhanHangs")
                        .HasForeignKey("IdKhachHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GiamGiaChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.GiamGia", "GiamGia")
                        .WithMany("GiamGiaChiTiets")
                        .HasForeignKey("IdGiamGia");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.HoaDon", "HoaDon")
                        .WithMany("GiamGiaChiTiets")
                        .HasForeignKey("IdHoaDon");

                    b.Navigation("GiamGia");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GioHang", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhachHang", "KhachHang")
                        .WithMany("GioHang")
                        .HasForeignKey("IdKhachHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GioHangChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.GioHang", "GioHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdGioHang");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.Navigation("GioHang");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.HoaDon", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.DiaChiNhanHang", "DiaChiNhanHang")
                        .WithMany("HoaDon")
                        .HasForeignKey("IdDiaChiNhanHang");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhachHang", "KhachHang")
                        .WithMany("HoaDon")
                        .HasForeignKey("IdKhachHang");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("HoaDon")
                        .HasForeignKey("IdPhuongThuc");

                    b.Navigation("DiaChiNhanHang");

                    b.Navigation("KhachHang");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.HoaDonChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHoaDon");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMaiPhanLoai", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.PhanLoai", "PhanLoai")
                        .WithMany("KKhuyenMaiPhanLoais")
                        .HasForeignKey("IdPhanLoai");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhuyenMai", "KhuyenMai")
                        .WithMany("KKhuyenMaiPhanLoais")
                        .HasForeignKey("idKhuyenMai");

                    b.Navigation("KhuyenMai");

                    b.Navigation("PhanLoai");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMaiSanPham", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("KKhuyenMaiSanPhams")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhuyenMai", "KhuyenMai")
                        .WithMany("KKhuyenMaiSanPhams")
                        .HasForeignKey("IdkhuyenMai");

                    b.Navigation("KhuyenMai");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.NhanVien", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.ChucVu", "ChucVu")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdChucVu");

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhanLoaiChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.PhanLoai", "PhanLoai")
                        .WithMany("PhanLoaiChiTiets")
                        .HasForeignKey("IdPhanLoai");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("PhanLoaiChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.Navigation("PhanLoai");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.ChatLieu", "ChatLieu")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdChatLieu");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.Mau", "Mau")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdMau");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.NSX", "NSX")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdNSX");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.Size", "Size")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdSize");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPham", "SanPham")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdSp");

                    b.Navigation("ChatLieu");

                    b.Navigation("Mau");

                    b.Navigation("NSX");

                    b.Navigation("SanPham");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamYeuThich", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhachHang", "KKhachHang")
                        .WithMany("SanPhamYeuThiches")
                        .HasForeignKey("IdKhachHang");

                    b.Navigation("KKhachHang");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChatLieu", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DanhMuc", b =>
                {
                    b.Navigation("DanhMucChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DiaChiNhanHang", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GiamGia", b =>
                {
                    b.Navigation("GiamGiaChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.HoaDon", b =>
                {
                    b.Navigation("GiamGiaChiTiets");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhachHang", b =>
                {
                    b.Navigation("DiaChiNhanHangs");

                    b.Navigation("GioHang");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamYeuThiches");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMai", b =>
                {
                    b.Navigation("KKhuyenMaiPhanLoais");

                    b.Navigation("KKhuyenMaiSanPhams");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Mau", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.NSX", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhanLoai", b =>
                {
                    b.Navigation("KKhuyenMaiPhanLoais");

                    b.Navigation("PhanLoaiChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhuongThucThanhToan", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPham", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", b =>
                {
                    b.Navigation("Anhs");

                    b.Navigation("CTietSanPhamYeuThiches");

                    b.Navigation("DanhMucChiTiets");

                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("KKhuyenMaiSanPhams");

                    b.Navigation("PhanLoaiChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamYeuThich", b =>
                {
                    b.Navigation("CTietSanPhamYeuThiches");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Size", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
