// <auto-generated />
using System;
using CTN4_Data.DB_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CTN4_Data.Migrations
{
    [DbContext(typeof(DB_CTN4_ok))]
    [Migration("20231011132342_b")]
    partial class b
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Anh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("TenAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("Anhs");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChatLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenChatLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ChatLieus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da84efc0-5fdd-444a-b737-e00ed4125020"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Da thuộc (real leather)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("9c7d47b9-9884-43d0-9a5d-c962ca7a124b"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Vải bông (Cotton)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("5b6c1cb0-e692-411f-874f-5fbd40eb4875"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Canvas",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("feb404b5-32ae-4153-b673-fe69d810fe34"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Nylon (Polyester)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("0a3235d6-eed9-4e21-bea6-c15d27612ab5"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Tricot (Vải dệt kim)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("a5265e86-5832-416e-9406-542bcf8835c0"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Vải không dệt (Micro Polyester)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("0a6aaca2-ff2f-4290-93d7-09ce4948fab1"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Vải Simili (Giả da)",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChiTietSanPhamYeuThich", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamYeuThich")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.HasIndex("IdSanPhamYeuThich");

                    b.ToTable("ChiTietSanPhamYeu");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChucVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ChucVus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d16ac357-3ced-4c2c-bcdc-d38971214414"),
                            TenChucVu = "Quản lý",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("56dd3ee2-c4df-4376-b982-e2c0f70877e9"),
                            TenChucVu = "Nhân viên",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DanhMuc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DanhMucs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b5dbef-5072-4bc8-9a49-967a190ad5f5"),
                            Is_detele = true,
                            TenDanhMuc = "Túi đeo chéo Nữ – Cross body"
                        },
                        new
                        {
                            Id = new Guid("abd11455-eb16-4235-9c1f-11596dc4cbad"),
                            Is_detele = true,
                            TenDanhMuc = "Túi đeo vai – Shoulder bag"
                        },
                        new
                        {
                            Id = new Guid("b94a865d-a984-476d-bcac-a7e4fd094639"),
                            Is_detele = true,
                            TenDanhMuc = "Túi tote"
                        },
                        new
                        {
                            Id = new Guid("0de8e41e-2e43-4a35-a973-0cff2e519c58"),
                            Is_detele = true,
                            TenDanhMuc = "Túi satchel"
                        },
                        new
                        {
                            Id = new Guid("a8d8522d-7ccb-436e-93de-f7bb2a3b3c63"),
                            Is_detele = true,
                            TenDanhMuc = "Túi baguette"
                        },
                        new
                        {
                            Id = new Guid("69e60e22-fed7-4f00-9880-e42bcac3b363"),
                            Is_detele = true,
                            TenDanhMuc = "Túi bao tử – Túi bumbag"
                        },
                        new
                        {
                            Id = new Guid("73de11a4-68a4-456f-adc9-a6031c81dd53"),
                            Is_detele = true,
                            TenDanhMuc = "Túi cầm tay – Clutch"
                        },
                        new
                        {
                            Id = new Guid("04ff52d9-5425-4efa-b96f-18389aed255a"),
                            Is_detele = true,
                            TenDanhMuc = "Túi Hobo"
                        },
                        new
                        {
                            Id = new Guid("1021cef9-436c-4a7b-8e8f-5409a67a5e95"),
                            Is_detele = true,
                            TenDanhMuc = "Túi dây rút – Pouch"
                        },
                        new
                        {
                            Id = new Guid("cecda21c-c255-4887-8245-d30b03913b56"),
                            Is_detele = true,
                            TenDanhMuc = "Túi Bucket"
                        },
                        new
                        {
                            Id = new Guid("0c204261-dac1-4929-9081-c5f3b0541b6c"),
                            Is_detele = true,
                            TenDanhMuc = "Túi Bowling"
                        },
                        new
                        {
                            Id = new Guid("f61c1505-f978-4cd0-bbe1-92003b02c1fe"),
                            Is_detele = true,
                            TenDanhMuc = "Túi Ring Bag"
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DanhMucChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDanhMuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdDanhMuc");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("DanhMucChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DiaChiNhanHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenDiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("DaiChiNhanHangs");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GiamGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("DieuKienGiam")
                        .HasColumnType("real");

                    b.Property<string>("MaGiam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<float>("SoTienGiam")
                        .HasColumnType("real");

                    b.Property<float>("SoTienGiamToiDa")
                        .HasColumnType("real");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GiamGias");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GiamGiaChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdGiamGia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdGiamGia");

                    b.HasIndex("IdHoaDon");

                    b.ToTable("GiamGiaChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GioHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdGioHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdGioHang");

                    b.ToTable("GioHangChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdDiaChiNhanHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPhuongThuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGiao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTaoHoaDon")
                        .HasColumnType("datetime2");

                    b.Property<float>("TongTien")
                        .HasColumnType("real");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDiaChiNhanHang");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdPhuongThuc");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("GiaTien")
                        .HasColumnType("real");

                    b.Property<Guid?>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("HoaDonChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhachHangs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d16ac357-3ced-4c2c-bcdc-d38971214499"),
                            AnhDaiDien = "",
                            DiaChi = "Hà Nội",
                            Email = "thieubvph20221@gmail.com",
                            GioiTinh = "Nam",
                            Ho = "Bùi Văm",
                            Is_detele = false,
                            MatKhau = "thieuxk",
                            SDT = "0912384746",
                            Ten = "Thiều",
                            TenDangNhap = "thieuxk",
                            Trangthai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_Detele")
                        .HasColumnType("bit");

                    b.Property<string>("MaKhuyenMai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanTramGiamGia")
                        .HasColumnType("int");

                    b.Property<float>("SoTienGiam")
                        .HasColumnType("real");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMaiPhanLoai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPhanLoai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("idKhuyenMai")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdPhanLoai");

                    b.HasIndex("idKhuyenMai");

                    b.ToTable("KhuyenMaiPhanLoais");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMaiSanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdkhuyenMai")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.HasIndex("IdkhuyenMai");

                    b.ToTable("KhuyenMaiSanPhams");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Mau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenMau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Maus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("09f80047-af89-46f9-8eb1-6c7d8f2c53e7"),
                            Is_detele = true,
                            TenMau = "đen",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("c340c7be-fe62-40d3-8b1d-ca216a99dc6b"),
                            Is_detele = true,
                            TenMau = "trắng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("ba346042-9aa3-4799-b343-302f64c6f2ae"),
                            Is_detele = true,
                            TenMau = "nâu da",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("5abef820-fcc6-4eda-b6fb-34d0800f8fa4"),
                            Is_detele = true,
                            TenMau = "xám",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("7b1f205b-c279-429f-966e-57b2092e73b4"),
                            Is_detele = true,
                            TenMau = "vàng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("81fec916-c8f4-4133-8f50-db944d887a16"),
                            Is_detele = true,
                            TenMau = "cam",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("04735728-2c78-45ab-9281-4fbbb34e3ae8"),
                            Is_detele = true,
                            TenMau = "xanh lục",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("d22e9df4-1080-4d9e-aa91-6061dfac1602"),
                            Is_detele = true,
                            TenMau = "xanh đương",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("9de2a347-f030-47f1-8d18-c890fcf2f13a"),
                            Is_detele = true,
                            TenMau = "tràm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("1e07ea31-731e-4795-8f7a-6560899a237d"),
                            Is_detele = true,
                            TenMau = "tím",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("0d27cae0-fb6c-4192-96b0-a77dd60eaa47"),
                            Is_detele = true,
                            TenMau = "xanh lá đậm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("163134ef-5848-4311-a242-552a2fae7a45"),
                            Is_detele = true,
                            TenMau = "hồng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("f54569fb-e350-4239-9642-74735b1b194e"),
                            Is_detele = true,
                            TenMau = "kem",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdChucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdChucVu");

                    b.ToTable("NhanViens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("339c88c6-fcbb-4d63-8792-6ae76150bfd3"),
                            AnhDaiDien = "",
                            DiaChi = "Hà Nội",
                            Email = "nothing@gmail.com",
                            GioiTinh = "Nữ",
                            Ho = "Nguyễn",
                            IdChucVu = new Guid("d16ac357-3ced-4c2c-bcdc-d38971214414"),
                            MatKhau = "12345678",
                            SDT = "0912384746",
                            Ten = "Trang",
                            TenDangNhap = "trangnt34",
                            Trangthai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.NSX", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenNSX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("NSXs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3339cb27-75ac-4541-88d7-8cc1eb10a7ba"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Juno",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("86e0e8df-4de0-412a-9680-d895817b60a8"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Prada",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("6ca542c2-ede5-44ec-9491-5bbbb42b2d0e"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Gucci",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("16d96346-bcd7-44e1-bddd-00eb19c0fbf2"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Chanel",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("0276512e-ef17-4098-9c79-713a8804a0b1"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Coach",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("f2387ca3-0045-4224-851f-9c158d9caef3"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "MLB Korea",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("ffd9950b-4e9a-42eb-906b-5acafb99be71"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Michael Kors",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("ef1971f6-b434-4f40-8ff5-02b9a833d443"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "JW Anderson",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("f6e6c13f-a5d3-4f3e-95c4-d760f6b9dbe7"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Christian Dior",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("6ea831bd-a9f3-4da6-b71c-529e6ed3f83f"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Louis Vuitton",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhanLoai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Delete")
                        .HasColumnType("bit");

                    b.Property<string>("TenPhanLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrạngThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PhanLoais");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhanLoaiChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPhanLoai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdPhanLoai");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("PhanLoaiChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhuongThucThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenPhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PhuongThucThanhToans");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("93dbb54b-1288-4038-aeca-27c8f27bbe6d"),
                            AnhDaiDien = "TXT Da Rắn Khóa Bạc _QuanChau_Trang_Da PU cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TXT Da Rắn Khóa Bạc _QuanChau_Trang_Da PU cao cấp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("30fa97a6-0385-4f4d-8845-1e3548375a1f"),
                            AnhDaiDien = "TXT Phủ Màu Tag Vuông_QuanChau_XanhLuc_Da PU mềm mịn, cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TXT Phủ Màu Tag Vuông_QuanChau_XanhLuc_Da PU mềm mịn, cao cấp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("d3a1957a-8a6e-466f-af83-7811c67b8109"),
                            AnhDaiDien = "TDV Hobo Đáy Tròn_QuanChau_Trang_Da lộn, da PU cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TDV Hobo Đáy Tròn_QuanChau_Trang_Da lộn, da PU cao cấp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("3fe711b1-ca23-41b1-a178-ce3913e1be12"),
                            AnhDaiDien = "Túi Xách Nhỏ Curve 1_Trung Quốc_Xanhduong_Da tổng hợp(1).webp",
                            Is_detele = true,
                            TenSanPham = "Túi Xách Nhỏ Curve 1_Trung Quốc_Xanhduong_Da tổng hợp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("523412ca-525e-4cfe-8ba9-b8a9b38f8881"),
                            AnhDaiDien = "TDV Hobo Đáy Tròn_QuanChau_Xanh-Duong_Da lộn, da PU cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TDV Hobo Đáy Tròn_QuanChau_Xanh-Duong_Da lộn, da PU cao cấp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("264f9c61-0764-4608-a8eb-03f9e62d9918"),
                            AnhDaiDien = "TOT Classic Phối Màu _QuanChau_Ghi_Da PU mềm mịn, cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TOT Classic Phối Màu _QuanChau_Ghi_Da PU mềm mịn, cao cấp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("3b759d9f-9ef1-40a4-a701-eec5f8bcf104"),
                            AnhDaiDien = "TOT Classic Phối Màu _QuanChau_Nau_Da PU mềm mịn, cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TOT Classic Phối Màu _QuanChau_Nau_Da PU mềm mịn, cao cấp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("e2f53939-e399-4537-b1d1-40e1f318bd96"),
                            AnhDaiDien = "Túi Xách Nhỏ Curve 1_Trung Quốc_XanhLa_Da tổng hợp(1).webp",
                            Is_detele = true,
                            TenSanPham = "Túi Xách Nhỏ Curve 1_Trung Quốc_XanhLa_Da tổng hợp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("ae94e90c-adef-4434-a4d4-d1a65e22772f"),
                            AnhDaiDien = "Túi Xách Nhỏ Đeo Vai - Cycling_Trung Quốc_XanhNhat_Da tổng hợp(1).webp",
                            Is_detele = true,
                            TenSanPham = "Túi Xách Nhỏ Đeo Vai - Cycling_Trung Quốc_XanhNhat_Da tổng hợp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("077b15b6-3b8a-4a26-b4fd-696283d361df"),
                            AnhDaiDien = "TDV Hobo Quai Ngắn_QuanChau_Trang_Da PU mềm mịn, cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TDV Hobo Quai Ngắn_QuanChau_Trang_Da PU mềm mịn, cao cấp(1)",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GiaBan")
                        .HasColumnType("real");

                    b.Property<float>("GiaNhap")
                        .HasColumnType("real");

                    b.Property<float>("GiaNiemYet")
                        .HasColumnType("real");

                    b.Property<Guid?>("IdChatLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMau")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNSX")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSize")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("MaSp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdChatLieu");

                    b.HasIndex("IdMau");

                    b.HasIndex("IdNSX");

                    b.HasIndex("IdSize");

                    b.HasIndex("IdSp");

                    b.ToTable("SanPhamChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamYeuThich", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("SanPhamYeuThichs");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bef11dda-b41f-4700-a05f-b08c63fa38e0"),
                            Is_detele = true,
                            TenSize = "Extra Small",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("4c94504c-17e9-4915-a845-bd07f9d18f6a"),
                            Is_detele = true,
                            TenSize = "Small",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("8ff0ef42-ca41-4887-ad74-b664e5c4348e"),
                            Is_detele = true,
                            TenSize = "Standard (Medium)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("cbf4eb7c-e0c9-47ce-afaf-71d991ed9903"),
                            Is_detele = true,
                            TenSize = "Large",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("ade68d53-4c87-415f-a22b-ac2c926a7367"),
                            Is_detele = true,
                            TenSize = "Extra Large",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Anh", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("Anhs")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChiTietSanPhamYeuThich", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("CTietSanPhamYeuThiches")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamYeuThich", "SanPhamYeuThich")
                        .WithMany("CTietSanPhamYeuThiches")
                        .HasForeignKey("IdSanPhamYeuThich");

                    b.Navigation("SanPhamChiTiet");

                    b.Navigation("SanPhamYeuThich");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DanhMucChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.DanhMuc", "DanhMuc")
                        .WithMany("DanhMucChiTiets")
                        .HasForeignKey("IdDanhMuc");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("DanhMucChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.Navigation("DanhMuc");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DiaChiNhanHang", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhachHang", "KhachHang")
                        .WithMany("DiaChiNhanHangs")
                        .HasForeignKey("IdKhachHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GiamGiaChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.GiamGia", "GiamGia")
                        .WithMany("GiamGiaChiTiets")
                        .HasForeignKey("IdGiamGia");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.HoaDon", "HoaDon")
                        .WithMany("GiamGiaChiTiets")
                        .HasForeignKey("IdHoaDon");

                    b.Navigation("GiamGia");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GioHang", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhachHang", "KhachHang")
                        .WithMany("GioHang")
                        .HasForeignKey("IdKhachHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GioHangChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.GioHang", "GioHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdGioHang");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdGioHang");

                    b.Navigation("GioHang");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.HoaDon", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.DiaChiNhanHang", "DiaChiNhanHang")
                        .WithMany("HoaDon")
                        .HasForeignKey("IdDiaChiNhanHang");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhachHang", "KhachHang")
                        .WithMany("HoaDon")
                        .HasForeignKey("IdKhachHang");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("HoaDon")
                        .HasForeignKey("IdPhuongThuc");

                    b.Navigation("DiaChiNhanHang");

                    b.Navigation("KhachHang");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.HoaDonChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHoaDon");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMaiPhanLoai", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.PhanLoai", "PhanLoai")
                        .WithMany("KKhuyenMaiPhanLoais")
                        .HasForeignKey("IdPhanLoai");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhuyenMai", "KhuyenMai")
                        .WithMany("KKhuyenMaiPhanLoais")
                        .HasForeignKey("idKhuyenMai");

                    b.Navigation("KhuyenMai");

                    b.Navigation("PhanLoai");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMaiSanPham", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("KKhuyenMaiSanPhams")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhuyenMai", "KhuyenMai")
                        .WithMany("KKhuyenMaiSanPhams")
                        .HasForeignKey("IdkhuyenMai");

                    b.Navigation("KhuyenMai");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.NhanVien", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.ChucVu", "ChucVu")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdChucVu");

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhanLoaiChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.PhanLoai", "PhanLoai")
                        .WithMany("PhanLoaiChiTiets")
                        .HasForeignKey("IdPhanLoai");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("PhanLoaiChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.Navigation("PhanLoai");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.ChatLieu", "ChatLieu")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdChatLieu");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.Mau", "Mau")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdMau");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.NSX", "NSX")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdNSX");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.Size", "Size")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdSize");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPham", "SanPham")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdSp");

                    b.Navigation("ChatLieu");

                    b.Navigation("Mau");

                    b.Navigation("NSX");

                    b.Navigation("SanPham");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamYeuThich", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhachHang", "KKhachHang")
                        .WithMany("SanPhamYeuThiches")
                        .HasForeignKey("IdKhachHang");

                    b.Navigation("KKhachHang");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChatLieu", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DanhMuc", b =>
                {
                    b.Navigation("DanhMucChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DiaChiNhanHang", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GiamGia", b =>
                {
                    b.Navigation("GiamGiaChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.HoaDon", b =>
                {
                    b.Navigation("GiamGiaChiTiets");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhachHang", b =>
                {
                    b.Navigation("DiaChiNhanHangs");

                    b.Navigation("GioHang");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamYeuThiches");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMai", b =>
                {
                    b.Navigation("KKhuyenMaiPhanLoais");

                    b.Navigation("KKhuyenMaiSanPhams");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Mau", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.NSX", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhanLoai", b =>
                {
                    b.Navigation("KKhuyenMaiPhanLoais");

                    b.Navigation("PhanLoaiChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhuongThucThanhToan", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPham", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", b =>
                {
                    b.Navigation("Anhs");

                    b.Navigation("CTietSanPhamYeuThiches");

                    b.Navigation("DanhMucChiTiets");

                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("KKhuyenMaiSanPhams");

                    b.Navigation("PhanLoaiChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamYeuThich", b =>
                {
                    b.Navigation("CTietSanPhamYeuThiches");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Size", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
