// <auto-generated />
using System;
using CTN4_Data.DB_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CTN4_Data.Migrations
{
    [DbContext(typeof(DB_CTN4_ok))]
    [Migration("20231010042750_bb")]
    partial class bb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Anh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SanPhamChiTietId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SanPhamChiTietId");

                    b.ToTable("Anhs");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChatLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenChatLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ChatLieus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c16e9a4-bc82-4f8e-b6b8-a19475f1b06c"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Da thuộc (real leather)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("c78cc68d-c3c3-48be-85c6-0cc162487cda"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Vải bông (Cotton)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("10dfcb09-547a-475a-8a4b-3b4368df9e11"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Canvas",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("8087bdc3-0bb0-45da-8303-683865025edb"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Nylon (Polyester)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("94a7d73b-0e10-4257-ad48-098ce791e130"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Tricot (Vải dệt kim)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("5b0c994b-60e8-4095-a543-b9b40ff3d991"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Vải không dệt (Micro Polyester)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("a4767ded-522b-496c-919f-cb477b273b23"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Vải Simili (Giả da)",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChiTietSanPhamYeuThich", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamYeuThich")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SanPhamChiTietId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SanPhamYeuThichId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SanPhamChiTietId");

                    b.HasIndex("SanPhamYeuThichId");

                    b.ToTable("ChiTietSanPhamYeu");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChucVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ChucVus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d16ac357-3ced-4c2c-bcdc-d38971214414"),
                            TenChucVu = "Quản lý",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("56dd3ee2-c4df-4376-b982-e2c0f70877e9"),
                            TenChucVu = "Nhân viên",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DanhMuc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DanhMucs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bcdd47ae-c392-4f09-9273-f0d531841ae1"),
                            Is_detele = true,
                            TenDanhMuc = "Túi đeo chéo Nữ – Cross body"
                        },
                        new
                        {
                            Id = new Guid("bde2fc22-4717-4234-8fa2-07fb913f3c9b"),
                            Is_detele = true,
                            TenDanhMuc = "Túi đeo vai – Shoulder bag"
                        },
                        new
                        {
                            Id = new Guid("46cf92f6-1719-48e6-a6ed-21d0af6a6165"),
                            Is_detele = true,
                            TenDanhMuc = "Túi tote"
                        },
                        new
                        {
                            Id = new Guid("6f3380f7-7ad3-4920-8a8f-013844390d2d"),
                            Is_detele = true,
                            TenDanhMuc = "Túi satchel"
                        },
                        new
                        {
                            Id = new Guid("8caec721-a44c-44af-8e4a-e6d4b6c04a9f"),
                            Is_detele = true,
                            TenDanhMuc = "Túi baguette"
                        },
                        new
                        {
                            Id = new Guid("64e9ab2a-c614-4f3a-968a-b6686b3a15a6"),
                            Is_detele = true,
                            TenDanhMuc = "Túi bao tử – Túi bumbag"
                        },
                        new
                        {
                            Id = new Guid("593654fa-c69d-46b0-8787-0cacb3a6aa57"),
                            Is_detele = true,
                            TenDanhMuc = "Túi cầm tay – Clutch"
                        },
                        new
                        {
                            Id = new Guid("bf6bc2a0-7eda-4189-8f08-9fc32525234e"),
                            Is_detele = true,
                            TenDanhMuc = "Túi Hobo"
                        },
                        new
                        {
                            Id = new Guid("13be67b1-3d8d-4387-a289-77ca17d5b78d"),
                            Is_detele = true,
                            TenDanhMuc = "Túi dây rút – Pouch"
                        },
                        new
                        {
                            Id = new Guid("394f2811-261b-424d-bed5-78857ced7038"),
                            Is_detele = true,
                            TenDanhMuc = "Túi Bucket"
                        },
                        new
                        {
                            Id = new Guid("ab25e2f3-7f7e-4675-8d98-9c605174c402"),
                            Is_detele = true,
                            TenDanhMuc = "Túi Bowling"
                        },
                        new
                        {
                            Id = new Guid("08f7b2f8-7820-4ed3-b851-6e543ef1dfc4"),
                            Is_detele = true,
                            TenDanhMuc = "Túi Ring Bag"
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DanhMucChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DanhMucId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDanhMuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SanPhamChiTietId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucId");

                    b.HasIndex("SanPhamChiTietId");

                    b.ToTable("DanhMucChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DiaChiNhanHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenDiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.ToTable("DaiChiNhanHangs");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GiamGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("DieuKienGiam")
                        .HasColumnType("real");

                    b.Property<string>("MaGiam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<float>("SoTienGiam")
                        .HasColumnType("real");

                    b.Property<float>("SoTienGiamToiDa")
                        .HasColumnType("real");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GiamGias");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GiamGiaChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GiamGiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdGiamGia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GiamGiaId");

                    b.HasIndex("HoaDonId");

                    b.ToTable("GiamGiaChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GioHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GioHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdGioHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SanPhamChiTietId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GioHangId");

                    b.HasIndex("SanPhamChiTietId");

                    b.ToTable("GioHangChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DiaChiNhanHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDiaChiNhanHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPhuongThuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGiao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTaoHoaDon")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PhuongThucThanhToanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("TongTien")
                        .HasColumnType("real");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiaChiNhanHangId");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("PhuongThucThanhToanId");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("GiaTien")
                        .HasColumnType("real");

                    b.Property<Guid?>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SanPhamChiTietId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("SanPhamChiTietId");

                    b.ToTable("HoaDonChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_Detele")
                        .HasColumnType("bit");

                    b.Property<string>("MaKhuyenMai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanTramGiamGia")
                        .HasColumnType("int");

                    b.Property<float>("SoTienGiam")
                        .HasColumnType("real");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMaiPhanLoai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPhanLoai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KhuyenMaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhanLoaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("idKhuyenMai")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("KhuyenMaiId");

                    b.HasIndex("PhanLoaiId");

                    b.ToTable("KhuyenMaiPhanLoais");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMaiSanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdkhuyenMai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KhuyenMaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SanPhamChiTietId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("KhuyenMaiId");

                    b.HasIndex("SanPhamChiTietId");

                    b.ToTable("KhuyenMaiSanPhams");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Mau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenMau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Maus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f36ba59a-0923-472d-8180-7a7117ef9c08"),
                            Is_detele = true,
                            TenMau = "đen",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("25453cdf-32c9-42c9-8b26-77a2a111d017"),
                            Is_detele = true,
                            TenMau = "trắng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("230227e4-dd5b-4997-b0c4-697041bb556d"),
                            Is_detele = true,
                            TenMau = "nâu da",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("f1ad46d4-c781-4456-afd3-9ca8d6d19263"),
                            Is_detele = true,
                            TenMau = "xám",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("2d9a596a-2f22-4b85-9ee2-e2fa1519d143"),
                            Is_detele = true,
                            TenMau = "vàng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("db126d6c-65a3-4e6f-a236-f5357fc395a1"),
                            Is_detele = true,
                            TenMau = "cam",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("0bd259ba-e2b2-4f80-9e5b-525df7321b34"),
                            Is_detele = true,
                            TenMau = "xanh lục",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("a84d9695-8977-481c-9c44-c3c8adc972b4"),
                            Is_detele = true,
                            TenMau = "xanh đương",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("c1ffeeaf-716e-45a3-8cd5-76e3af904daf"),
                            Is_detele = true,
                            TenMau = "tràm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("ac20489d-fcff-4662-b5cc-279172a5fe65"),
                            Is_detele = true,
                            TenMau = "tím",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("e7ec0db4-40fe-4545-84ea-c2759fa81e27"),
                            Is_detele = true,
                            TenMau = "xanh lá đậm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("d072dbd7-b072-4140-800a-2ffc0ab70a49"),
                            Is_detele = true,
                            TenMau = "hồng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("d9d94fdb-2304-4343-8b81-8b214675c9de"),
                            Is_detele = true,
                            TenMau = "kem",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ChucVuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdChucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ChucVuId");

                    b.ToTable("NhanViens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66b2d9e0-6780-4ae9-a914-017b4e48636e"),
                            AnhDaiDien = "",
                            DiaChi = "Hà Nội",
                            Email = "nothing@gmail.com",
                            GioiTinh = "Nữ",
                            Ho = "Nguyễn",
                            MatKhau = "12345678",
                            SDT = "0912384746",
                            Ten = "Trang",
                            TenDangNhap = "trangnt34",
                            Trangthai = true
                        },
                        new
                        {
                            Id = new Guid("1d92b01f-51f5-435c-a00e-77e711cc4626"),
                            AnhDaiDien = "",
                            DiaChi = "Ninh Bình",
                            Email = "nothing2@gmail.com",
                            GioiTinh = "Nam",
                            Ho = "Trần",
                            MatKhau = "12345678",
                            SDT = "0819265834",
                            Ten = "Hà",
                            TenDangNhap = "Hatl12",
                            Trangthai = true
                        },
                        new
                        {
                            Id = new Guid("2e02294a-b2bc-447b-ae62-4e8a74a4726a"),
                            AnhDaiDien = "",
                            DiaChi = "Bình Thuận",
                            Email = "nothing3@gmail.com",
                            GioiTinh = "Nam",
                            Ho = "Lê",
                            MatKhau = "12345678",
                            SDT = "0817236583",
                            Ten = "Minh",
                            TenDangNhap = "Leminh66",
                            Trangthai = true
                        },
                        new
                        {
                            Id = new Guid("17c931be-14ac-47fa-a4d3-7687374aaeca"),
                            AnhDaiDien = "",
                            DiaChi = "thành phố Hồ Chí Minh",
                            Email = "nothing4@gmail.com",
                            GioiTinh = "Nam",
                            Ho = "Phùng",
                            MatKhau = "12345678",
                            SDT = "0129837582",
                            Ten = "Hoàng",
                            TenDangNhap = "Hoangpv14",
                            Trangthai = true
                        },
                        new
                        {
                            Id = new Guid("069bebe6-5b92-40fd-a682-c2e75ff7bf96"),
                            AnhDaiDien = "",
                            DiaChi = "Quảng Ninh",
                            Email = "nothing5@gmail.com",
                            GioiTinh = "Nữ",
                            Ho = "Bùi",
                            MatKhau = "12345678",
                            SDT = "0982647912",
                            Ten = "Huyền",
                            TenDangNhap = "Huyenbt62",
                            Trangthai = true
                        },
                        new
                        {
                            Id = new Guid("efb8fbda-0960-4562-b4d9-42f89d49a2f0"),
                            AnhDaiDien = "",
                            DiaChi = "New York",
                            Email = "nothing6@gmail.com",
                            GioiTinh = "Nam",
                            Ho = "Kenny",
                            MatKhau = "12345678",
                            SDT = "0576947384",
                            Ten = "Nguyen",
                            TenDangNhap = "kennynguyen145",
                            Trangthai = true
                        },
                        new
                        {
                            Id = new Guid("989df993-6ba3-43ce-bde4-58173d88b567"),
                            AnhDaiDien = "",
                            DiaChi = "Hà Nội",
                            Email = "nothing9@gmail.com",
                            GioiTinh = "Nam",
                            Ho = "Báo thủ",
                            MatKhau = "12345678",
                            SDT = "0975846374",
                            Ten = "Bách",
                            TenDangNhap = "Bachbaothu13",
                            Trangthai = true
                        },
                        new
                        {
                            Id = new Guid("d2708b44-8e7a-49ad-8818-6f53bdd89af4"),
                            AnhDaiDien = "",
                            DiaChi = "Paris",
                            Email = "nothing7@gmail.com",
                            GioiTinh = "Nam",
                            Ho = "Trần",
                            MatKhau = "12345678",
                            SDT = "0292304805",
                            Ten = "Boss",
                            TenDangNhap = "Bosshidden69",
                            Trangthai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.NSX", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenNSX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("NSXs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("87219100-9c30-40c2-876c-70adfb6103d2"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Juno",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("5b5f79e8-bb4c-4fa7-b5d5-7470dc82990f"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Prada",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("476485af-d28a-4ea2-a9c0-fc139cda6077"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Gucci",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("6dce2907-9877-4817-bcfd-5d34d56344e8"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Chanel",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("5350a100-8017-4921-a2a5-6bebe58c6e8b"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Coach",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("82d1cbbc-3696-49b8-b53d-3c22710c8e3d"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "MLB Korea",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("bd3ca336-61a4-4e08-9d1c-5604716233dd"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Michael Kors",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("8d22ff06-ccac-4c3f-b857-5c1b5ace9e5d"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "JW Anderson",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("75f9f5d5-7740-4ed5-8527-3d1e34de3e47"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Christian Dior",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("55a9a67d-ce04-4552-8ace-0bb96fd1edcc"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Louis Vuitton",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhanLoai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Delete")
                        .HasColumnType("bit");

                    b.Property<string>("TenPhanLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrạngThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PhanLoais");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhanLoaiChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPhanLoai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhanLoaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SanPhamChiTietId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PhanLoaiId");

                    b.HasIndex("SanPhamChiTietId");

                    b.ToTable("PhanLoaiChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhuongThucThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenPhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PhuongThucThanhToans");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhDaiDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("71db160c-8166-41ee-9a0f-ffffaa6cc229"),
                            AnhDaiDiem = "",
                            Is_detele = true,
                            TenSanPham = "Túi Xách Nhỏ Hobo Dập Logo Jn",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("aeae4fea-f02a-4ae6-a935-f1cd54e3f875"),
                            AnhDaiDiem = "",
                            Is_detele = true,
                            TenSanPham = "Túi Xách Nhỏ Top Handle Cozy",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("2a34f4d2-ce2a-4a20-8196-6d9e67423f42"),
                            AnhDaiDiem = "",
                            Is_detele = true,
                            TenSanPham = "Túi Xách Nhỏ Top Handle Phối Hoa 3D",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("49911f86-ff4f-4a82-9511-ddebe4d6162c"),
                            AnhDaiDiem = "",
                            Is_detele = true,
                            TenSanPham = "Túi Xách Nhỏ Shoulder Bag Trang Trí Khóa Logo Cách Điệu",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("e936d974-9225-47e0-b13a-a61aae0e133b"),
                            AnhDaiDiem = "",
                            Is_detele = true,
                            TenSanPham = "Túi Xách Nhỏ Dây Kéo Phối 2 Chất Liệu",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("11534d46-18b8-44e4-86ef-e79a8ac98b19"),
                            AnhDaiDiem = "",
                            Is_detele = true,
                            TenSanPham = "Túi Xách Nhỏ Dáng Boho New Moon",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("b41b4f46-7d66-4ed5-873a-df108271741a"),
                            AnhDaiDiem = "",
                            Is_detele = true,
                            TenSanPham = "Túi Xách Nhỏ Đeo Vai Elite Of The Class",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("5329490b-fab2-420a-8d1e-74ecb914fc34"),
                            AnhDaiDiem = "",
                            Is_detele = true,
                            TenSanPham = "Túi Xách Nhỏ Nắp Gập Khóa Trang Trí",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("4099a96e-e403-4e60-b715-f3b887c4addc"),
                            AnhDaiDiem = "",
                            Is_detele = true,
                            TenSanPham = "Túi Xách Nhỏ Đeo Vai Time Travelling",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("df4fb58d-e697-4adf-870e-eaba682e0d32"),
                            AnhDaiDiem = "",
                            Is_detele = true,
                            TenSanPham = "Túi Xách Nhỏ Hobo Time Travelling",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChatLieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GiaBan")
                        .HasColumnType("real");

                    b.Property<float>("GiaNhap")
                        .HasColumnType("real");

                    b.Property<float>("GiaNiemYet")
                        .HasColumnType("real");

                    b.Property<Guid?>("IdChatLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMau")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNSX")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSize")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("MaSp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NSXId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SizeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ChatLieuId");

                    b.HasIndex("MauId");

                    b.HasIndex("NSXId");

                    b.HasIndex("SanPhamId");

                    b.HasIndex("SizeId");

                    b.ToTable("SanPhamChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamYeuThich", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KKhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("KKhachHangId");

                    b.ToTable("SanPhamYeuThichs");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a48b5a77-e329-4e7b-8494-1279d551e0b1"),
                            Is_detele = true,
                            TenSize = "Extra Small",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("ada9450d-ceb9-4523-b9d3-89396e215d61"),
                            Is_detele = true,
                            TenSize = "Small",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("d5480587-203d-41b4-9962-eba3d40fbed7"),
                            Is_detele = true,
                            TenSize = "Standard (Medium)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("8217080b-e781-463f-8119-ca3d426a44e6"),
                            Is_detele = true,
                            TenSize = "Large",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("d03c10d7-8a8f-47f0-b7a2-a97a7ae7a6e0"),
                            Is_detele = true,
                            TenSize = "Extra Large",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Anh", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("Anhs")
                        .HasForeignKey("SanPhamChiTietId");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChiTietSanPhamYeuThich", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("CTietSanPhamYeuThiches")
                        .HasForeignKey("SanPhamChiTietId");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamYeuThich", "SanPhamYeuThich")
                        .WithMany("CTietSanPhamYeuThiches")
                        .HasForeignKey("SanPhamYeuThichId");

                    b.Navigation("SanPhamChiTiet");

                    b.Navigation("SanPhamYeuThich");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DanhMucChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.DanhMuc", "DanhMuc")
                        .WithMany("DanhMucChiTiets")
                        .HasForeignKey("DanhMucId");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("DanhMucChiTiets")
                        .HasForeignKey("SanPhamChiTietId");

                    b.Navigation("DanhMuc");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DiaChiNhanHang", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhachHang", "KhachHang")
                        .WithMany("DiaChiNhanHangs")
                        .HasForeignKey("KhachHangId");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GiamGiaChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.GiamGia", "GiamGia")
                        .WithMany("GiamGiaChiTiets")
                        .HasForeignKey("GiamGiaId");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.HoaDon", "HoaDon")
                        .WithMany("GiamGiaChiTiets")
                        .HasForeignKey("HoaDonId");

                    b.Navigation("GiamGia");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GioHang", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhachHang", "KhachHang")
                        .WithMany("GioHang")
                        .HasForeignKey("KhachHangId");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GioHangChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.GioHang", "GioHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("GioHangId");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("SanPhamChiTietId");

                    b.Navigation("GioHang");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.HoaDon", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.DiaChiNhanHang", "DiaChiNhanHang")
                        .WithMany("HoaDon")
                        .HasForeignKey("DiaChiNhanHangId");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhachHang", "KhachHang")
                        .WithMany("HoaDon")
                        .HasForeignKey("KhachHangId");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("HoaDon")
                        .HasForeignKey("PhuongThucThanhToanId");

                    b.Navigation("DiaChiNhanHang");

                    b.Navigation("KhachHang");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.HoaDonChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("HoaDonId");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("SanPhamChiTietId");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMaiPhanLoai", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhuyenMai", "KhuyenMai")
                        .WithMany("KKhuyenMaiPhanLoais")
                        .HasForeignKey("KhuyenMaiId");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.PhanLoai", "PhanLoai")
                        .WithMany("KKhuyenMaiPhanLoais")
                        .HasForeignKey("PhanLoaiId");

                    b.Navigation("KhuyenMai");

                    b.Navigation("PhanLoai");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMaiSanPham", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhuyenMai", "KhuyenMai")
                        .WithMany("KKhuyenMaiSanPhams")
                        .HasForeignKey("KhuyenMaiId");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("KKhuyenMaiSanPhams")
                        .HasForeignKey("SanPhamChiTietId");

                    b.Navigation("KhuyenMai");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.NhanVien", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.ChucVu", "ChucVu")
                        .WithMany("NhanViens")
                        .HasForeignKey("ChucVuId");

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhanLoaiChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.PhanLoai", "PhanLoai")
                        .WithMany("PhanLoaiChiTiets")
                        .HasForeignKey("PhanLoaiId");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("PhanLoaiChiTiets")
                        .HasForeignKey("SanPhamChiTietId");

                    b.Navigation("PhanLoai");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.ChatLieu", "ChatLieu")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("ChatLieuId");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.Mau", "Mau")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("MauId");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.NSX", "NSX")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("NSXId");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPham", "SanPham")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("SanPhamId");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.Size", "Size")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("SizeId");

                    b.Navigation("ChatLieu");

                    b.Navigation("Mau");

                    b.Navigation("NSX");

                    b.Navigation("SanPham");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamYeuThich", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhachHang", "KKhachHang")
                        .WithMany("SanPhamYeuThiches")
                        .HasForeignKey("KKhachHangId");

                    b.Navigation("KKhachHang");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChatLieu", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DanhMuc", b =>
                {
                    b.Navigation("DanhMucChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DiaChiNhanHang", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GiamGia", b =>
                {
                    b.Navigation("GiamGiaChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.HoaDon", b =>
                {
                    b.Navigation("GiamGiaChiTiets");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhachHang", b =>
                {
                    b.Navigation("DiaChiNhanHangs");

                    b.Navigation("GioHang");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamYeuThiches");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMai", b =>
                {
                    b.Navigation("KKhuyenMaiPhanLoais");

                    b.Navigation("KKhuyenMaiSanPhams");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Mau", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.NSX", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhanLoai", b =>
                {
                    b.Navigation("KKhuyenMaiPhanLoais");

                    b.Navigation("PhanLoaiChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhuongThucThanhToan", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPham", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", b =>
                {
                    b.Navigation("Anhs");

                    b.Navigation("CTietSanPhamYeuThiches");

                    b.Navigation("DanhMucChiTiets");

                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("KKhuyenMaiSanPhams");

                    b.Navigation("PhanLoaiChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamYeuThich", b =>
                {
                    b.Navigation("CTietSanPhamYeuThiches");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Size", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
