// <auto-generated />
using System;
using CTN4_Data.DB_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CTN4_Data.Migrations
{
    [DbContext(typeof(DB_CTN4_ok))]
    partial class DB_CTN4_okModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Anh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("TenAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("Anhs");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChatLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenChatLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ChatLieus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11a58cf1-2a35-463a-846c-393a8263ae5a"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Da PU cao cấp",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("2571a49c-cafd-44b5-b097-ac7d9b0bcd96"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Da PU mềm mịn, cao cấp",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("f76c7f09-4deb-4d83-8115-b28d222e52f4"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Vai Canvat",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("ce521b50-a065-4d1d-8933-28be59d1129a"),
                            GhiChu = "",
                            Is_detele = true,
                            TenChatLieu = "Da tổng hợp",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChiTietSanPhamYeuThich", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamYeuThich")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.HasIndex("IdSanPhamYeuThich");

                    b.ToTable("ChiTietSanPhamYeu");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChucVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ChucVus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d16ac357-3ced-4c2c-bcdc-d38971214414"),
                            TenChucVu = "Quản lý",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("56dd3ee2-c4df-4376-b982-e2c0f70877e9"),
                            TenChucVu = "Nhân viên",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DanhMuc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DanhMucs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9f1af17-d9c6-4590-8de5-6420c3536413"),
                            Is_detele = true,
                            TenDanhMuc = "Túi đeo chéo Nữ – Cross body"
                        },
                        new
                        {
                            Id = new Guid("5035f0b8-4ced-459b-9893-d0fe202c3d23"),
                            Is_detele = true,
                            TenDanhMuc = "Túi đeo vai – Shoulder bag"
                        },
                        new
                        {
                            Id = new Guid("be61710b-46b4-4856-be3a-f52a7c181201"),
                            Is_detele = true,
                            TenDanhMuc = "Túi tote"
                        },
                        new
                        {
                            Id = new Guid("8bf6369f-f17a-437d-837e-93a4e2c042f8"),
                            Is_detele = true,
                            TenDanhMuc = "Túi satchel"
                        },
                        new
                        {
                            Id = new Guid("202fe108-4dc4-43ef-81df-dc8c27d069be"),
                            Is_detele = true,
                            TenDanhMuc = "Túi baguette"
                        },
                        new
                        {
                            Id = new Guid("3add2fec-6a29-437f-b044-9269e6d92831"),
                            Is_detele = true,
                            TenDanhMuc = "Túi bao tử – Túi bumbag"
                        },
                        new
                        {
                            Id = new Guid("d71949ec-7f01-43cf-9eb9-349aa26215c3"),
                            Is_detele = true,
                            TenDanhMuc = "Túi cầm tay – Clutch"
                        },
                        new
                        {
                            Id = new Guid("ec6c3419-3a19-483f-8e1b-4a02c22dfde0"),
                            Is_detele = true,
                            TenDanhMuc = "Túi Hobo"
                        },
                        new
                        {
                            Id = new Guid("0f7f8edf-ed4b-4f9e-ba8d-1631bb564cb9"),
                            Is_detele = true,
                            TenDanhMuc = "Túi dây rút – Pouch"
                        },
                        new
                        {
                            Id = new Guid("87cf4a90-90ca-44c7-8cdb-7648f89a19ae"),
                            Is_detele = true,
                            TenDanhMuc = "Túi Bucket"
                        },
                        new
                        {
                            Id = new Guid("ede7be32-49b2-4a9b-9b7a-c1a1bccbde66"),
                            Is_detele = true,
                            TenDanhMuc = "Túi Bowling"
                        },
                        new
                        {
                            Id = new Guid("c9b613dc-87f7-4414-aeb0-5ab459242437"),
                            Is_detele = true,
                            TenDanhMuc = "Túi Ring Bag"
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DanhMucChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDanhMuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdDanhMuc");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("DanhMucChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DiaChiNhanHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenDiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("DaiChiNhanHangs");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GiamGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("DieuKienGiam")
                        .HasColumnType("real");

                    b.Property<string>("MaGiam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<float>("SoTienGiam")
                        .HasColumnType("real");

                    b.Property<float>("SoTienGiamToiDa")
                        .HasColumnType("real");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GiamGias");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GiamGiaChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdGiamGia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdGiamGia");

                    b.HasIndex("IdHoaDon");

                    b.ToTable("GiamGiaChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GioHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdGioHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdGioHang");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("GioHangChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdDiaChiNhanHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPhuongThuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGiao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTaoHoaDon")
                        .HasColumnType("datetime2");

                    b.Property<float>("TongTien")
                        .HasColumnType("real");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDiaChiNhanHang");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdPhuongThuc");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("GiaTien")
                        .HasColumnType("real");

                    b.Property<Guid?>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("HoaDonChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhachHangs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d16ac357-3ced-4c2c-bcdc-d38971214499"),
                            AnhDaiDien = "",
                            DiaChi = "Hà Nội",
                            Email = "thieubvph20221@gmail.com",
                            GioiTinh = "Nam",
                            Ho = "Bùi Văm",
                            Is_detele = true,
                            MatKhau = "thieuxk",
                            SDT = "0912384746",
                            Ten = "Thiều",
                            TenDangNhap = "thieuxk",
                            Trangthai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_Detele")
                        .HasColumnType("bit");

                    b.Property<string>("MaKhuyenMai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanTramGiamGia")
                        .HasColumnType("int");

                    b.Property<float>("SoTienGiam")
                        .HasColumnType("real");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMaiPhanLoai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPhanLoai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("idKhuyenMai")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdPhanLoai");

                    b.HasIndex("idKhuyenMai");

                    b.ToTable("KhuyenMaiPhanLoais");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMaiSanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdkhuyenMai")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.HasIndex("IdkhuyenMai");

                    b.ToTable("KhuyenMaiSanPhams");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Mau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenMau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Maus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ff4f69d1-1381-473e-8103-13e1471c0ea0"),
                            Is_detele = true,
                            TenMau = "đen",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("13431a98-cf18-4628-a3de-409c114b3298"),
                            Is_detele = true,
                            TenMau = "trắng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("83e1a80f-baf5-4337-83a1-10bd0fa3a2a0"),
                            Is_detele = true,
                            TenMau = "nâu",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("d1241870-b01a-4832-b2aa-3ed0f9e7dfd6"),
                            Is_detele = true,
                            TenMau = "xám",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("5e5be10e-ca75-4ccb-a4df-0932a1b864fc"),
                            Is_detele = true,
                            TenMau = "vàng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("c2f13edf-2390-4201-8a2c-c9d609bb1e46"),
                            Is_detele = true,
                            TenMau = "ghi",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("612ea65a-7ad0-45aa-ba59-2d0628514286"),
                            Is_detele = true,
                            TenMau = "cam",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("35c5c671-2c81-4cf4-8720-481a60919a2e"),
                            Is_detele = true,
                            TenMau = "xanh dương đậm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("363fe4e9-c8b0-47d4-b610-6ec7b78b9ff6"),
                            Is_detele = true,
                            TenMau = "xanh lục",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("d28a8a35-c195-453f-ad51-8b6e208b8bf1"),
                            Is_detele = true,
                            TenMau = "xanh dương",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("5768d1e6-ecd1-4f6e-978b-c5cbc19c2d4b"),
                            Is_detele = true,
                            TenMau = "xanh lá",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("d3e7bb9e-d9d9-4f13-a4e1-88be4387eefc"),
                            Is_detele = true,
                            TenMau = "xanh nhạt",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("47dbd6c4-b552-41ae-96c9-2898c0e18ebc"),
                            Is_detele = true,
                            TenMau = "tràm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("6d17f685-b5a4-40e1-adc6-50a35a866982"),
                            Is_detele = true,
                            TenMau = "tím",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("4a63b31f-3e1c-4ccc-968b-e377e3d9bda5"),
                            Is_detele = true,
                            TenMau = "xanh lá đậm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("8eff5a22-0fa8-402d-a0f4-3369671d0465"),
                            Is_detele = true,
                            TenMau = "xanh tím",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("a3f674bc-e5d7-4aad-bc6e-8583b5d34229"),
                            Is_detele = true,
                            TenMau = "hồng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("6cc26505-2331-496d-a4c3-76652b629594"),
                            Is_detele = true,
                            TenMau = "kem",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("5dd16586-6973-426a-a78e-c6901b41d7d1"),
                            Is_detele = true,
                            TenMau = "kem Đậm",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdChucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdChucVu");

                    b.ToTable("NhanViens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("828b17b0-0ae9-488d-bcdc-187794c53797"),
                            AnhDaiDien = "",
                            DiaChi = "Hà Nội",
                            Email = "nothing@gmail.com",
                            GioiTinh = "Nữ",
                            Ho = "Nguyễn",
                            IdChucVu = new Guid("d16ac357-3ced-4c2c-bcdc-d38971214414"),
                            MatKhau = "12345678",
                            SDT = "0912384746",
                            Ten = "Trang",
                            TenDangNhap = "trangnt34",
                            Trangthai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.NSX", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenNSX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("NSXs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da8feee4-e2ba-4b43-a6f7-4a7ffef5cab3"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Juno",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("e00cccba-9e13-4a58-be90-78699664f47a"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Prada",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("ec6c31ea-ae1c-443b-823f-39a40bcb2c5d"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Gucci",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("cdf2ed3d-7a3e-4366-943a-8782953b587e"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Chanel",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("a41d9a2a-b9dd-4214-a6a3-495185bce92e"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Coach",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("7160525e-175f-4143-b15c-767281288b2b"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "MLB Korea",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("287442f6-e66e-4383-a82f-620b27c7aaa9"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Michael Kors",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("46658551-a636-4852-869e-d9d2106daa29"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "JW Anderson",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("efd9c330-93b0-4065-bde9-7287c9e26519"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Christian Dior",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("37a4019f-40fb-42a0-ae0a-b412aef3ef13"),
                            GhiChu = "",
                            Is_detele = true,
                            TenNSX = "Louis Vuitton",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhanLoai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Delete")
                        .HasColumnType("bit");

                    b.Property<string>("TenPhanLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrạngThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PhanLoais");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhanLoaiChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPhanLoai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdPhanLoai");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("PhanLoaiChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhuongThucThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenPhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PhuongThucThanhToans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d16ac357-3ced-4c2c-bcdc-d38971211111"),
                            Is_detele = true,
                            TenPhuongThuc = "Thanh toán khi nhận hàng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("d16ac357-3ced-4c2c-bcdc-d38971211112"),
                            Is_detele = true,
                            TenPhuongThuc = "Thanh toán tại cửa hàng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("d16ac357-3ced-4c2c-bcdc-d38971211113"),
                            Is_detele = true,
                            TenPhuongThuc = "Thanh toán qua ngân hàng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("d16ac357-3ced-4c2c-bcdc-d38971211114"),
                            Is_detele = true,
                            TenPhuongThuc = "Thanh toán qua VNpay",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0daa94fb-89ef-439b-a084-c6fae66b6db6"),
                            AnhDaiDien = "TXT Da Rắn Khóa Bạc _QuanChau_Trang_Da PU cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TXT Da Rắn Khóa Bạc _QuanChau_Trang_Da PU cao cấp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("81c17f13-7db0-46a6-b83e-d210e4b19d7a"),
                            AnhDaiDien = "TXT Phủ Màu Tag Vuông_QuanChau_XanhLuc_Da PU mềm mịn, cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TXT Phủ Màu Tag Vuông_QuanChau_XanhLuc_Da PU mềm mịn, cao cấp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("33b07e93-a0ce-473b-ac37-b24a8bdb4ad3"),
                            AnhDaiDien = "TDV Hobo Đáy Tròn_QuanChau_Trang_Da lộn, da PU cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TDV Hobo Đáy Tròn_QuanChau_Trang_Da lộn, da PU cao cấp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("36ffe385-f22b-4381-a766-87b37815a77c"),
                            AnhDaiDien = "Túi Xách Nhỏ Curve 1_Trung Quốc_Xanhduong_Da tổng hợp(1).webp",
                            Is_detele = true,
                            TenSanPham = "Túi Xách Nhỏ Curve 1_Trung Quốc_Xanhduong_Da tổng hợp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("55207b59-91b4-4fe7-88da-459268e04b98"),
                            AnhDaiDien = "TDV Hobo Đáy Tròn_QuanChau_Xanh-Duong_Da lộn, da PU cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TDV Hobo Đáy Tròn_QuanChau_Xanh-Duong_Da lộn, da PU cao cấp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("b2e88dfb-ad3f-4c89-872e-09d1196192ca"),
                            AnhDaiDien = "TOT Classic Phối Màu _QuanChau_Ghi_Da PU mềm mịn, cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TOT Classic Phối Màu _QuanChau_Ghi_Da PU mềm mịn, cao cấp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("b7e2517a-4f29-410d-aa14-3adf036c267e"),
                            AnhDaiDien = "TOT Classic Phối Màu _QuanChau_Nau_Da PU mềm mịn, cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TOT Classic Phối Màu _QuanChau_Nau_Da PU mềm mịn, cao cấp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("3b4e8333-af58-435a-a3fe-8bf347fd23b1"),
                            AnhDaiDien = "Túi Xách Nhỏ Curve 1_Trung Quốc_XanhLa_Da tổng hợp(1).webp",
                            Is_detele = true,
                            TenSanPham = "Túi Xách Nhỏ Curve 1_Trung Quốc_XanhLa_Da tổng hợp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("4b96ab38-6a17-4b61-9ab2-afdcf8707902"),
                            AnhDaiDien = "Túi Xách Nhỏ Đeo Vai - Cycling_Trung Quốc_XanhNhat_Da tổng hợp(1).webp",
                            Is_detele = true,
                            TenSanPham = "Túi Xách Nhỏ Đeo Vai - Cycling_Trung Quốc_XanhNhat_Da tổng hợp(1)",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("c621dd2f-640e-4d08-8fd1-f2cbcb28758d"),
                            AnhDaiDien = "TDV Hobo Quai Ngắn_QuanChau_Trang_Da PU mềm mịn, cao cấp(1).jpg",
                            Is_detele = true,
                            TenSanPham = "TDV Hobo Quai Ngắn_QuanChau_Trang_Da PU mềm mịn, cao cấp(1)",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GiaBan")
                        .HasColumnType("real");

                    b.Property<float>("GiaNhap")
                        .HasColumnType("real");

                    b.Property<float>("GiaNiemYet")
                        .HasColumnType("real");

                    b.Property<Guid?>("IdChatLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMau")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNSX")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSize")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("MaSp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdChatLieu");

                    b.HasIndex("IdMau");

                    b.HasIndex("IdNSX");

                    b.HasIndex("IdSize");

                    b.HasIndex("IdSp");

                    b.ToTable("SanPhamChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamYeuThich", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("SanPhamYeuThichs");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Is_detele")
                        .HasColumnType("bit");

                    b.Property<string>("TenSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbd5ee29-93c9-48fb-a70a-48b1c7df05f1"),
                            Is_detele = true,
                            TenSize = "30cm x 20cm x 10cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("1fb37c42-1c4d-4486-934c-19b83349bd67"),
                            Is_detele = true,
                            TenSize = "28cm x 22cm x 10cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("dddee698-4ab7-47d5-a537-8128568cfb8a"),
                            Is_detele = true,
                            TenSize = "27cm x 12cm x 8cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("09127eff-8783-48bc-8008-1014431cfc47"),
                            Is_detele = true,
                            TenSize = "23cm x 13cm x 6cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("29064b95-128d-4e8b-9c14-7973a0274260"),
                            Is_detele = true,
                            TenSize = "23cm x 15cm x 5cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("462c5bad-4ed7-45d7-96fe-3aa08aea2b63"),
                            Is_detele = true,
                            TenSize = "22cm x 18cm x 8cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("3914e2ec-e0d5-47c2-b35c-e172a7635b3d"),
                            Is_detele = true,
                            TenSize = "20cm x 12cm x 7cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("7a773b5a-d519-49b9-89aa-3efd440752eb"),
                            Is_detele = true,
                            TenSize = "22cm x 15cm x 6cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("5e6b449e-7b79-4a8b-a8f3-f85b89a6c94d"),
                            Is_detele = true,
                            TenSize = "17cm x 16cm x 7cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("68784dfa-b674-44ad-a88b-4a97683ea623"),
                            Is_detele = true,
                            TenSize = "22cm x 12cm x 6cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("88f47a21-51c2-41e5-a33e-ab80327b455e"),
                            Is_detele = true,
                            TenSize = "21cm x 8cm x 13cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("b7eceefd-df2f-41f5-acb9-4301fb512e79"),
                            Is_detele = true,
                            TenSize = "27cm x 6cm x 19cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("6ae17509-d2d1-452f-b9e1-38d62a7c0811"),
                            Is_detele = true,
                            TenSize = "20cm x 6cm x 13cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("238231e3-0eae-4355-9447-0ca4b077fe55"),
                            Is_detele = true,
                            TenSize = "37cm x 13cm x 28cm",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("ee0211d5-26fe-4c5c-b1b9-e718f58e2f49"),
                            Is_detele = true,
                            TenSize = "20cm x 13.5cm x 7.5cm ",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("fb4cb218-ea67-4997-9ea6-ebeeedf7abb4"),
                            Is_detele = true,
                            TenSize = "19cm x 13cm x 7cm",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Anh", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("Anhs")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChiTietSanPhamYeuThich", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("CTietSanPhamYeuThiches")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamYeuThich", "SanPhamYeuThich")
                        .WithMany("CTietSanPhamYeuThiches")
                        .HasForeignKey("IdSanPhamYeuThich");

                    b.Navigation("SanPhamChiTiet");

                    b.Navigation("SanPhamYeuThich");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DanhMucChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.DanhMuc", "DanhMuc")
                        .WithMany("DanhMucChiTiets")
                        .HasForeignKey("IdDanhMuc");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("DanhMucChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.Navigation("DanhMuc");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DiaChiNhanHang", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhachHang", "KhachHang")
                        .WithMany("DiaChiNhanHangs")
                        .HasForeignKey("IdKhachHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GiamGiaChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.GiamGia", "GiamGia")
                        .WithMany("GiamGiaChiTiets")
                        .HasForeignKey("IdGiamGia");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.HoaDon", "HoaDon")
                        .WithMany("GiamGiaChiTiets")
                        .HasForeignKey("IdHoaDon");

                    b.Navigation("GiamGia");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GioHang", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhachHang", "KhachHang")
                        .WithMany("GioHang")
                        .HasForeignKey("IdKhachHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GioHangChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.GioHang", "GioHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdGioHang");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.Navigation("GioHang");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.HoaDon", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.DiaChiNhanHang", "DiaChiNhanHang")
                        .WithMany("HoaDon")
                        .HasForeignKey("IdDiaChiNhanHang");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhachHang", "KhachHang")
                        .WithMany("HoaDon")
                        .HasForeignKey("IdKhachHang");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("HoaDon")
                        .HasForeignKey("IdPhuongThuc");

                    b.Navigation("DiaChiNhanHang");

                    b.Navigation("KhachHang");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.HoaDonChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHoaDon");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMaiPhanLoai", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.PhanLoai", "PhanLoai")
                        .WithMany("KKhuyenMaiPhanLoais")
                        .HasForeignKey("IdPhanLoai");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhuyenMai", "KhuyenMai")
                        .WithMany("KKhuyenMaiPhanLoais")
                        .HasForeignKey("idKhuyenMai");

                    b.Navigation("KhuyenMai");

                    b.Navigation("PhanLoai");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMaiSanPham", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("KKhuyenMaiSanPhams")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhuyenMai", "KhuyenMai")
                        .WithMany("KKhuyenMaiSanPhams")
                        .HasForeignKey("IdkhuyenMai");

                    b.Navigation("KhuyenMai");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.NhanVien", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.ChucVu", "ChucVu")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdChucVu");

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhanLoaiChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.PhanLoai", "PhanLoai")
                        .WithMany("PhanLoaiChiTiets")
                        .HasForeignKey("IdPhanLoai");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("PhanLoaiChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet");

                    b.Navigation("PhanLoai");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.ChatLieu", "ChatLieu")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdChatLieu");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.Mau", "Mau")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdMau");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.NSX", "NSX")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdNSX");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.Size", "Size")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdSize");

                    b.HasOne("CTN4_Data.Models.DB_CTN4.SanPham", "SanPham")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdSp");

                    b.Navigation("ChatLieu");

                    b.Navigation("Mau");

                    b.Navigation("NSX");

                    b.Navigation("SanPham");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamYeuThich", b =>
                {
                    b.HasOne("CTN4_Data.Models.DB_CTN4.KhachHang", "KKhachHang")
                        .WithMany("SanPhamYeuThiches")
                        .HasForeignKey("IdKhachHang");

                    b.Navigation("KKhachHang");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChatLieu", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DanhMuc", b =>
                {
                    b.Navigation("DanhMucChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.DiaChiNhanHang", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GiamGia", b =>
                {
                    b.Navigation("GiamGiaChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.HoaDon", b =>
                {
                    b.Navigation("GiamGiaChiTiets");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhachHang", b =>
                {
                    b.Navigation("DiaChiNhanHangs");

                    b.Navigation("GioHang");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamYeuThiches");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.KhuyenMai", b =>
                {
                    b.Navigation("KKhuyenMaiPhanLoais");

                    b.Navigation("KKhuyenMaiSanPhams");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Mau", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.NSX", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhanLoai", b =>
                {
                    b.Navigation("KKhuyenMaiPhanLoais");

                    b.Navigation("PhanLoaiChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.PhuongThucThanhToan", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPham", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamChiTiet", b =>
                {
                    b.Navigation("Anhs");

                    b.Navigation("CTietSanPhamYeuThiches");

                    b.Navigation("DanhMucChiTiets");

                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("KKhuyenMaiSanPhams");

                    b.Navigation("PhanLoaiChiTiets");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.SanPhamYeuThich", b =>
                {
                    b.Navigation("CTietSanPhamYeuThiches");
                });

            modelBuilder.Entity("CTN4_Data.Models.DB_CTN4.Size", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
